### ISSUE TITLE
X-Frame Options = Deny

### ISSUE THREAD

**Issue by russokiwi** [zolderio/AITMWorker#3]
Hi, thanks for the script! I'd like to make it work with BITM but keep getting connection denied in the iframe because X-Frame Options is set to deny.  How do I adjust the script / settings to make it X-Frame Options allow from https://example.com/* for example?

**Comment by ixdrop** [comment]
> Hi, thanks for the script! I'd like to make it work with BITM but keep getting connection denied in the iframe because X-Frame Options is set to deny. How do I adjust the script / settings to make it X-Frame Options allow from https://example.com/* for example?

have you figured this out? i am having the same issue.
