### ISSUE TITLE
Add Turnstile (captcha) to worker?

### ISSUE THREAD

**Issue by hardinxcore** [zolderio/AITMWorker#5]
Added own/custom url to the worker. Within a short time I got Netcraft takedown notice to my accounts at Cloudflare and Registrar. 

Only used it on own tenants. 

How to add Turnstile so automatic scanners like Netcraft do not find my worker.

**Comment by ZolderBV** [comment]
Hi, please read https://developers.cloudflare.com/turnstile/get-started/ to see how to add it :)
